### ISSUE TITLE
Segfault when inserting elements

### ISSUE THREAD

**Issue by myshen96** [rusnikola/lfqueue#2]
I tried to measure the performance of concurrent enqueue, so I commented out the dequeue in the benchmark function in pairwise.c like this:
```C
void * benchmark(int id, int nprocs) {
  void * val = (void *) (intptr_t) (id + 1);
  handle_t * th = hds[id];

  delay_t state;
  delay_init(&state, id);

  int i;
  for (i = 0; i < nops / nprocs; ++i) {
    enqueue(q, th, val);
//    delay_exec(&state);

//    val = dequeue(q, th);
//    delay_exec(&state);
  }

  return val;
}
```

Then I just ran the benchmark with the command `./wcq 20 6`. It directly triggered the segmentation fault in the first iteration.
```
===========================================
  Benchmark: ./wcq
  Number of processors: 20
  Number of operations: 1000000
[1]    2125267 segmentation fault (core dumped)  ./wcq 20 6
```

I tried debugging and found that the `tail` in function __wfring_slow_inc points to somewhere wrong, but I could find the reason which caused it. I guess it is because the number of elements I tried to insert is too big, but it should not trigger a segmentation fault, so there might be a bug here.

```
Thread 2 "wcq" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff68ff700 (LWP 2126476)]
0x0000555555555ba9 in __wfring_slow_inc (global=0x7ffff6900100, local=0x7ffff4a00040, prev=0x4047c,
    threshold=0x0, phase2=0x7ffff4a00018) at ../wfring_cas2.h:264
264                             if (*prev & __WFRING_FIN) return false;
(gdb) bt
#0  0x0000555555555ba9 in __wfring_slow_inc (global=0x7ffff6900100, local=0x7ffff4a00040, prev=0x4047c,
    threshold=0x0, phase2=0x7ffff4a00018) at ../wfring_cas2.h:264
#1  0x000055555555658b in __wfring_do_enqueue_slow (q=0x7ffff6900000, order=15, eidx=65533, seq=1,
    tail=263292, nonempty=false, state=0x7ffff4a00000) at ../wfring_cas2.h:301
#2  0x00005555555566b6 in __wfring_enqueue_slow (q=0x7ffff6900000, order=15, eidx=65533, tail=263292,
    nonempty=false, state=0x7ffff4a00000) at ../wfring_cas2.h:366
#3  0x0000555555557799 in wfring_enqueue (ring=0x7ffff6900000, order=15, eidx=65533, nonempty=false,
    state=0x7ffff4a00000) at ../wfring_cas2.h:573
#4  0x0000555555557cea in enqueue (q=0x7ffff6900000, th=0x7ffff4a00000, val=0x2) at wcq.c:33
#5  0x0000555555558ad3 in benchmark (id=1, nprocs=20) at pairwise.c:50
#6  0x00005555555582c8 in thread (bits=0x100000014) at harness.c:129
#7  0x00007ffff7cc0609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#8  0x00007ffff7a96163 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

@rusnikola Is it possible you could help with this? Thanks for the great work and the open-source code.

**Comment by rusnikola** [comment]
@myshen96 I will take a look at this. But this is not necessarily a bug since, as you mentioned, the number of elements exceeds the size of the ring buffer, which will break many assumptions.

**Comment by myshen96** [comment]
@rusnikola Thanks for your reply! If the number of elements exceeding the ring buffer size will trigger seg fault, does it mean the enqueuer should check if the queue is full before enqueuing?

**Comment by rusnikola** [comment]
@myshen96 Sorry that it took so long to get back, as I was not initially sure whether this bug report was valid (due to the testing conditions). It turned out to be a bug actually. It looks like the latest version of wCQ somehow got a typo/bug in one place, which I have fixed. Since your stack trace shows a crash in the same place, I assume it should also fix this particular issue.

**Comment by rusnikola** [comment]
Should be now fixed

**Comment by myshen96** [comment]
Thanks!
